# Generated by Django 2.2.2 on 2020-05-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
