# Generated by Django 2.2.2 on 2020-05-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waters', '0002_auto_20200514_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(default='1.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
