# Generated by Django 2.2.2 on 2020-05-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waters', '0006_auto_20200518_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
